$ ->
  do PORTAL.setTopLevelLayout
  do PORTAL.prepareMap
  do PORTAL.createControllers
  do PORTAL.activateLayers
  do PORTAL.activateMapLocations
  do PORTAL.activateAdmin
  do PORTAL.activateAdminAddSource
  do PORTAL.finishMap
